name: restaurantreviewer
channels:
  - conda-forge
dependencies:
  - python=3.13
  - selenium
  - webdriver-manager
  - tqdm
  - beautifulsoup4
  - lxml
  - pandas
  - matplotlib
  - scikit-learn
  - ipykernel
  - wordcloud
  - seaborn
  - openai
  - python-dotenv
  - pip
  - pip:
      - deep-translator